# -*- coding: utf-8 -*-
"""AB,Phonepe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GjLx7AzFZCsFIo__LM1ly2uYJzK2fvGu
"""

!git clone https://github.com/PhonePe/pulse.git

import os
path="/content/pulse/data/aggregated/transaction/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

#Once created the clone of GIT-HUB repository then,
#Required libraries for the program

import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path="/content/pulse/data/aggregated/transaction/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/" #"/content/pulse/data/aggregated/transaction/country/india/state/assam/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"#"/content/pulse/data/aggregated/transaction/country/india/state/assam/2018/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k #"/content/pulse/data/aggregated/transaction/country/india/state/assam/2018/1.json"
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transacion_type'].append(Name)
              clm['Transacion_count'].append(count)
              clm['Transacion_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Agg_Trans=pd.DataFrame(clm)

import plotly.express as px

fig = px.bar(
    Agg_Trans,
    x="Transacion_type",
    y="Transacion_amount",
    color="Transacion_type",
    title="Transaction Amount by Type"
)

fig.show()

year_data = Agg_Trans.groupby("Year")["Transacion_amount"].sum().reset_index()

fig = px.line(
    year_data,
    x="Year",
    y="Transacion_amount",
    title="Total Transaction Growth Over Years"
)

fig.show()

state_data = Agg_Trans.groupby("State")["Transacion_amount"].sum().reset_index()

fig = px.bar(
    state_data,
    x="State",
    y="Transacion_amount",
    title="State Wise Transaction Amount"
)

fig.show()

top_states = Agg_Trans.groupby("State")["Transacion_amount"].sum().reset_index()

top_states = top_states.sort_values(by="Transacion_amount", ascending=False).head(10)

fig = px.bar(
    top_states,
    x="State",
    y="Transacion_amount",
    title="Top 10 States by Transaction Amount"
)

fig.show()

Agg_Trans

len(Agg_Trans['State'].unique())

state_trans = Agg_Trans.groupby("State")["Transacion_amount"].sum().reset_index()
state_trans

state_trans["State"] = state_trans["State"].str.replace("-", " ")
state_trans["State"] = state_trans["State"].str.title()

import plotly.express as px

fig = px.choropleth(
    state_trans,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey="properties.ST_NM",
    locations="State",
    color="Transacion_amount",
    color_continuous_scale="greens",
    title="PhonePe Transaction Amount by State"
)

fig.update_geos(fitbounds="locations", visible=False)

fig.show()

df

Agg_Trans.to_csv("phonepe_transactions.csv", index=False)